# password Makefile

CAPABILITY_ID = "medio:interfaces:password"
NAME = "password"
VENDOR = "Acme"
PROJECT = password
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

