# time Makefile

CAPABILITY_ID = "medio:interfaces:time"
NAME = "time"
VENDOR = "Acme"
PROJECT = time
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

