# authtoken Makefile

CAPABILITY_ID = "medio:interfaces:authtoken"
NAME = "authtoken"
VENDOR = "Acme"
PROJECT = authtoken
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

