// This file is @generated by wasmcloud/weld-codegen 0.7.0.
// It is not intended for manual editing.
// namespace: org.kny.interfaces.time

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// wasmbus.contractId: medio:interfaces:time
/// wasmbus.providerReceive
/// wasmbus.actorReceive
#[async_trait]
pub trait Time {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "medio:interfaces:time"
    }
    /// Return current time as number of seconds since unix epoch
    async fn now(&self, ctx: &Context) -> RpcResult<u64>;
}

/// TimeReceiver receives messages defined in the Time service trait
#[doc(hidden)]
#[async_trait]
pub trait TimeReceiver: MessageDispatch + Time {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "Now" => {
                let resp = Time::now(self, ctx).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Time::{}",
                message.method
            ))),
        }
    }
}

/// TimeSender sends messages to a Time service
/// client for sending Time messages
#[derive(Clone, Debug)]
pub struct TimeSender<T: Transport> {
    transport: T,
}

impl<T: Transport> TimeSender<T> {
    /// Constructs a TimeSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> TimeSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl TimeSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}

#[cfg(target_arch = "wasm32")]
impl TimeSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for sending to a Time provider
    /// implementing the 'medio:interfaces:time' capability contract, with the "default" link
    pub fn new() -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_provider("medio:interfaces:time", "default")
                .unwrap();
        Self { transport }
    }

    /// Constructs a client for sending to a Time provider
    /// implementing the 'medio:interfaces:time' capability contract, with the specified link name
    pub fn new_with_link(link_name: &str) -> wasmbus_rpc::error::RpcResult<Self> {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_provider("medio:interfaces:time", link_name)?;
        Ok(Self { transport })
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Time for TimeSender<T> {
    #[allow(unused)]
    /// Return current time as number of seconds since unix epoch
    async fn now(&self, ctx: &Context) -> RpcResult<u64> {
        let buf = *b"";
        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Time.Now",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: u64 = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': U64", e)))?;
        Ok(value)
    }
}
