name = "newsletter"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:messaging", "wasmcloud:sqldb", "wasmcloud:builtin:logging", "medio:interfaces:email"]
call_alias = "medio_newsletters"
