[[models]]
path = "../interface"
files = [
    "user.smithy",
]

[[models]]
url = "https://wasmcloud.github.io/interfaces/idl/org.wasmcloud"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

[html]
output_dir = "html"
[html.parameters]
minified = true

[rust]
output_dir = "."

[rust.parameters]

[[rust.files]]
path = "src/user.rs"
namespace = "org.kny.medio.user"
