# email Makefile

CAPABILITY_ID = "medio:interfaces:email"
NAME = "email"
VENDOR = "Acme"
PROJECT = email
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

